schema = 3

[mod]
  [mod."ariga.io/atlas"]
    version = "v0.19.1-0.20240203083654-5948b60a8e43"
    hash = "sha256-wyuU3hcy3FbPa7iXCTGTKJ5oZH0D2SjzUZiHDGfcE+Q="
  [mod."entgo.io/ent"]
    version = "v0.14.0"
    hash = "sha256-jPgmUUOMcn5tJJMkO0oUsq15VAU5RxtK+UuYY158vXs="
  [mod."github.com/KyleBanks/depth"]
    version = "v1.2.1"
    hash = "sha256-czR52MfeKA2FdStXCebTMQRKT8jaWQcbV214O3j49qU="
  [mod."github.com/PuerkitoBio/purell"]
    version = "v1.1.1"
    hash = "sha256-Hjf8ZNNdwcRd50A9QNrcCj17gu/6f1iKzVTVrrMrojA="
  [mod."github.com/PuerkitoBio/urlesc"]
    version = "v0.0.0-20170810143723-de5bf2ad4578"
    hash = "sha256-nL0/0QM0Pec83vBlwXvQ8g5SvvZnCQgzD1apxfHNGlg="
  [mod."github.com/adrg/xdg"]
    version = "v0.5.0"
    hash = "sha256-hYxtRzeFzT+4zbslWSZWmUJf+OBDmCiwL0D/0Ry8Z2I="
  [mod."github.com/agext/levenshtein"]
    version = "v1.2.1"
    hash = "sha256-SuFgpvp7KGO4f2t0KnkhSUv7iRI7oGq40CjRc1tLNr4="
  [mod."github.com/apparentlymart/go-textseg/v13"]
    version = "v13.0.0"
    hash = "sha256-Hn+zO0J/vnG5U6JvZfRyWm8vsqYdjh4RAreWnZLCQKQ="
  [mod."github.com/bytedance/sonic"]
    version = "v1.12.1"
    hash = "sha256-IUln7rJO4hXzDbaWgVaJEMxYXN2LmXrbaCu7GNqdq5w="
  [mod."github.com/bytedance/sonic/loader"]
    version = "v0.2.0"
    hash = "sha256-Ea5oUG/riGBJRKTT4IS2caEYHWJ322KwTGJ2T+xXJ6I="
  [mod."github.com/cloudwego/base64x"]
    version = "v0.1.4"
    hash = "sha256-umCZR3iNmHFm+BC76kfpdcRG+pTQd6Jcu/c2kQDnyfw="
  [mod."github.com/cloudwego/iasm"]
    version = "v0.2.0"
    hash = "sha256-TzIP2N3HOesXrKACsRr/ShcoqttwPGZPckIepsTyHOA="
  [mod."github.com/fatih/color"]
    version = "v1.17.0"
    hash = "sha256-QsKMy3MsvjbYNcA9jP8w6c3wpmWDZ0079bybAEzmXR0="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.7.0"
    hash = "sha256-MdT2rQyQHspPJcx6n9ozkLbsktIOJutOqDuKpNAtoZY="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.5"
    hash = "sha256-Vv/+Et/6G+eFKehBx1dhqommo/bs7qXrgDzzu18G4FM="
  [mod."github.com/gin-contrib/sse"]
    version = "v0.1.0"
    hash = "sha256-zYbMTao+1F+385Lvsba9roLmmt9eYqr57sUWo0LCVhw="
  [mod."github.com/gin-contrib/zap"]
    version = "v1.1.4"
    hash = "sha256-f+cmhV290jxNLNa7BQ2NKVZBtp+5BU+NJb5gR+fg+bI="
  [mod."github.com/gin-gonic/gin"]
    version = "v1.10.0"
    hash = "sha256-esJasHrJtuTBwGPGAoc/XSb428J8va+tPGcZ0gTfsgc="
  [mod."github.com/go-openapi/inflect"]
    version = "v0.19.0"
    hash = "sha256-jS969dMoR2zLfVfsIQoQIbATyE5p2mIZfW9SnxY7W68="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.5"
    hash = "sha256-rLyvUdTMeQGeWiVsz2ZeyyFjHomeqd0x+ZR77mxi8Ss="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.19.6"
    hash = "sha256-yR7L193fc/w/96+S8l4Nv8NwLq1cDsZiNu3TD195naw="
  [mod."github.com/go-openapi/spec"]
    version = "v0.20.4"
    hash = "sha256-upjAukxFt+zpxxt7+X59910T9JgAn39D/5bl5E0Uib0="
  [mod."github.com/go-openapi/swag"]
    version = "v0.19.15"
    hash = "sha256-NWIJ5GDWMbRc9r8ZPy7PiA7lnlTWYgM5NucwRhkP3zs="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.22.0"
    hash = "sha256-P4K54M9nkXJgJBEPUUXp1TJ7tzw43vtVJ4p/hy8Gzn0="
  [mod."github.com/go-viper/mapstructure/v2"]
    version = "v2.0.0"
    hash = "sha256-GNOL2Ef1d3X3DCh7/HS9k127CdJmugm0YIiK0iEekdI="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.3"
    hash = "sha256-ZOzfwCXh+qp+hp+UnC0t422hUV0Cq5KANXkx8hcLp7s="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/google/uuid"]
    version = "v1.4.0"
    hash = "sha256-FU0gzLmS48Ik9T+quGg5z/7ESGMPSXM3SY+rdJtG+5w="
  [mod."github.com/hashicorp/hcl/v2"]
    version = "v2.13.0"
    hash = "sha256-Y67be1wd7PI7Rmc4tX3klCE7fCokhZuvbXFmbfD1Htc="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.8"
    hash = "sha256-/E58BnABQYxO+cmiue7OQqRLWkd/Lh8grX8DjTU4tk8="
  [mod."github.com/leodido/go-urn"]
    version = "v1.4.0"
    hash = "sha256-Q6kplWkY37Tzy6GOme3Wut40jFK4Izun+ij/BJvcEu0="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.6"
    hash = "sha256-lObieB06Ep7xL3Bbc1sxWpAeqH9VH2LXsPIc9uueuXs="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mitchellh/go-wordwrap"]
    version = "v0.0.0-20150314170334-ad45545899c7"
    hash = "sha256-aR+xW4TnVo96Cbw168fhdIBEh7O43mOlHdLx/WxrwVs="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.2"
    hash = "sha256-ukxk1Cfm6cQW18g/aa19tLcUu5BnF7VmfAvrDHAOl6A="
  [mod."github.com/sagikazarmark/locafero"]
    version = "v0.6.0"
    hash = "sha256-uAanQ7NRa13axM4zbOgMOyU+YhLALsQyT85XvqEdx2c="
  [mod."github.com/sourcegraph/conc"]
    version = "v0.3.0"
    hash = "sha256-mIdMs9MLAOBKf3/0quf1iI3v8uNWydy7ae5MFa+F2Ko="
  [mod."github.com/spf13/afero"]
    version = "v1.11.0"
    hash = "sha256-+rV3cDZr13N8E0rJ7iHmwsKYKH+EhV+IXBut+JbBiIE="
  [mod."github.com/spf13/cast"]
    version = "v1.6.0"
    hash = "sha256-hxioqRZfXE0AE5099wmn3YG0AZF8Wda2EB4c7zHF6zI="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.1"
    hash = "sha256-yDF6yAHycV1IZOrt3/hofR+QINe+B2yqkcIaVov3Ky8="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.20.0-alpha.6"
    hash = "sha256-qdOzeJl82Mdl70VsPaT+C8z5PW7jbTJFGEIl7wWQlgo="
  [mod."github.com/subosito/gotenv"]
    version = "v1.6.0"
    hash = "sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A="
  [mod."github.com/swaggo/files"]
    version = "v1.0.1"
    hash = "sha256-bNBmpJaM7g1BNwd7VxNIRSdY35NKSXhYHGfnZsSEUZ8="
  [mod."github.com/swaggo/gin-swagger"]
    version = "v1.6.0"
    hash = "sha256-hvX6co7b9Xmhl29ACMvTcD1TTRbI5178r+DRlabgMwY="
  [mod."github.com/swaggo/swag"]
    version = "v1.16.3"
    hash = "sha256-BBzm733YaghTzoSuKVVwF/9ae8ifP849GVsLFd9It8Q="
  [mod."github.com/twitchyliquid64/golang-asm"]
    version = "v0.15.1"
    hash = "sha256-HLk6oUe7EoITrNvP0y8D6BtIgIcmDZYtb/xl/dufIoY="
  [mod."github.com/ugorji/go/codec"]
    version = "v1.2.12"
    hash = "sha256-sp1LJ93UK7mFwgZqG8jxCgTCPgKR74HNU6XxX0Jfjm0="
  [mod."github.com/zclconf/go-cty"]
    version = "v1.8.0"
    hash = "sha256-Sf4mCSBV8e53x8nI0YPgZHivNWmUseWc26AtTdcUv4c="
  [mod."go.uber.org/dig"]
    version = "v1.18.0"
    hash = "sha256-aaMuKzGe0U8iZzsRUNQXmMIdKoQ3Fn6t6xpSNb82hcE="
  [mod."go.uber.org/fx"]
    version = "v1.22.2"
    hash = "sha256-2GYji8JlRJeqQKyPwittnb0TT6sJK5J+kDG1dNkpOqc="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."golang.org/x/arch"]
    version = "v0.9.0"
    hash = "sha256-P2D3rfWpgoppzsPFiwz4ZLwkYEPunW22zqXx7tsm5Ko="
  [mod."golang.org/x/crypto"]
    version = "v0.26.0"
    hash = "sha256-Iicrsb65fCmjfPILKoSLyBZMwe2VUcoTF5SpYTCQEuk="
  [mod."golang.org/x/mod"]
    version = "v0.17.0"
    hash = "sha256-CLaPeF6uTFuRDv4oHwOQE6MCMvrzkUjWN3NuyywZjKU="
  [mod."golang.org/x/net"]
    version = "v0.28.0"
    hash = "sha256-WdH/mgsX/CB+CiYtXEwJAXHN8FgtW2YhFcWwrrHNBLo="
  [mod."golang.org/x/sys"]
    version = "v0.24.0"
    hash = "sha256-P0fsA+qy9taYHWPTtCs5XmrJ1i8tWfvkno+PNuc2elw="
  [mod."golang.org/x/text"]
    version = "v0.17.0"
    hash = "sha256-R8JbsP7KX+KFTHH7SjRnUGCdvtagylVOfngWEnVSqBc="
  [mod."golang.org/x/tools"]
    version = "v0.21.1-0.20240508182429-e35e4ccd0d2d"
    hash = "sha256-KfnS+3fREPAWQUBoUedPupQp9yLrugxMmmEoHvyzKNE="
  [mod."google.golang.org/protobuf"]
    version = "v1.34.2"
    hash = "sha256-nMTlrDEE2dbpWz50eQMPBQXCyQh4IdjrTIccaU0F3m0="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.2.1"
    hash = "sha256-GaXWRDxhGy4Z4mgE+bJ8OE9SVvYUa9TnNiydnp2s1Ms="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
