// Code generated by ogen, DO NOT EDIT.

package ogent

// setDefaults set default value of fields.
func (s *CreateJudgeReq) setDefaults() {
	{
		val := CreateJudgeReqType("local")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *CreateSubmissionReq) setDefaults() {
	{
		val := CreateSubmissionReqStatus("pending")
		s.Status = val
	}
	{
		val := CreateSubmissionReqVerdict("OK")
		s.Verdict = val
	}
}

// setDefaults set default value of fields.
func (s *JudgeCreate) setDefaults() {
	{
		val := JudgeCreateType("local")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *JudgeList) setDefaults() {
	{
		val := JudgeListType("local")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *JudgeRead) setDefaults() {
	{
		val := JudgeReadType("local")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *JudgeUpdate) setDefaults() {
	{
		val := JudgeUpdateType("local")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *ProblemJudgeRead) setDefaults() {
	{
		val := ProblemJudgeReadType("local")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *ProblemSubmissionsList) setDefaults() {
	{
		val := ProblemSubmissionsListStatus("pending")
		s.Status = val
	}
	{
		val := ProblemSubmissionsListVerdict("OK")
		s.Verdict = val
	}
}

// setDefaults set default value of fields.
func (s *SubmissionCreate) setDefaults() {
	{
		val := SubmissionCreateStatus("pending")
		s.Status = val
	}
	{
		val := SubmissionCreateVerdict("OK")
		s.Verdict = val
	}
}

// setDefaults set default value of fields.
func (s *SubmissionList) setDefaults() {
	{
		val := SubmissionListStatus("pending")
		s.Status = val
	}
	{
		val := SubmissionListVerdict("OK")
		s.Verdict = val
	}
}

// setDefaults set default value of fields.
func (s *SubmissionRead) setDefaults() {
	{
		val := SubmissionReadStatus("pending")
		s.Status = val
	}
	{
		val := SubmissionReadVerdict("OK")
		s.Verdict = val
	}
}

// setDefaults set default value of fields.
func (s *SubmissionUpdate) setDefaults() {
	{
		val := SubmissionUpdateStatus("pending")
		s.Status = val
	}
	{
		val := SubmissionUpdateVerdict("OK")
		s.Verdict = val
	}
}

// setDefaults set default value of fields.
func (s *UpdateJudgeReq) setDefaults() {
	{
		val := UpdateJudgeReqType("local")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateSubmissionReq) setDefaults() {
	{
		val := UpdateSubmissionReqStatus("pending")
		s.Status.SetTo(val)
	}
	{
		val := UpdateSubmissionReqVerdict("OK")
		s.Verdict.SetTo(val)
	}
}
