basePath: /v1
definitions:
  healthz.Result:
    properties:
      details:
        $ref: '#/definitions/healthz.ResultDetails'
      status:
        enum:
        - ok
        - error
        example: ok
        type: string
      uptime:
        type: string
    type: object
  healthz.ResultDetail:
    properties:
      error:
        type: string
      status:
        enum:
        - ok
        - error
        example: ok
        type: string
    type: object
  healthz.ResultDetails:
    properties:
      db:
        $ref: '#/definitions/healthz.ResultDetail'
    type: object
info:
  contact: {}
  description: This is a API for running SYOI Online Judge.
  license:
    name: GNU General Public License (GPLv3)
    url: https://www.gnu.org/licenses/gpl-3.0.html
  title: SYOI Online Judge API
  version: "1.0"
paths:
  /healthz:
    get:
      description: Health Checking for API services
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthz.Result'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/healthz.Result'
      summary: Health Checking
swagger: "2.0"
