// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Judge is the predicate function for judge builders.
type Judge func(*sql.Selector)

// Problem is the predicate function for problem builders.
type Problem func(*sql.Selector)

// Submission is the predicate function for submission builders.
type Submission func(*sql.Selector)
